#!/bin/sh

sudo apt-get install docker-ce
curl -L https://github.com/docker/compose/releases/download/1.11.2/run.sh > docker-compose
sudo mv docker-compose /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo usermod -aG docker $USER
