#!/bin/bash

if [ ! -e $HOME/.gvm ] ; then
    bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
    GOVERSION=go1.3.3
    source $HOME/.gvm/scripts/gvm

    gvm install $GOVERSION
    gvm use $GOVERSION --default
fi
