#!/bin/bash

if [ ! -e $HOME/go ] ; then
    curl -sSL https://storage.googleapis.com/golang/go1.5.2.linux-amd64.tar.gz > /tmp/go.tar.gz
    tar -xvzf /tmp/go.tar.gz -C $HOME
    rm /tmp/go.tar.gz
fi
