#!/bin/sh

node_version=`nodenv install -l | grep -E "^[ 0-9\.]+$" | sort -V | tail -n 1`
if [ -z `nodenv versions | grep $node_version` ]; then
    nodenv install $node_version
    nodenv global $node_version
fi
