#!/bin/sh

if [ ! -e $HOME/.oh-my-zsh ] ; then
    curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
    chsh -s /bin/zsh
    sed -ie '/export PATH=/{/\$PATH/!d;}' ~/.zshrc
fi
