#!/bin/sh

sudo apt-get -y install\
 build-essential texinfo autoconf automake\
 google-chrome-stable\
 dropbox\
 git gitk\
 mercurial\
 zsh\
 lv\
 rlwrap\
 tmux\
 vim emacs\
 fcitx-mozc\
 curl libcurl4-openssl-dev\
 libreadline6-dev\
 bison\
 sqlite3 libsqlite3-dev\
 libxml2 libxml2-dev\
 libxslt1.1 libxslt1-dev\
 openssh-server libssl-dev\
 nkf\
 libv8-dev\
 compizconfig-settings-manager\
 convmv\
 libdbus-glib-1-dev\
 libmysql++-dev\
 libpq-dev\
 redis-server\
 xsel\
 libsasl2-dev\
 imagemagick libmagickcore-dev\
 libav-tools\
 colordiff\
 texlive texlive-lang-cjk\
 fonts-ipafont\
 python-pip\
 ansible

hash -r
