#!/bin/sh

python_version=`pyenv install -l | grep -E "^[ 0-9\.]+$" | sort -V | tail -n 1`
if [ -z `pyenv versions | grep $python_version` ]; then
    pyenv install $python_version
    pyenv global $python_version
fi
