#!/bin/bash

RUBY_VERSION=ruby-2.6.3

if [ ! -e $HOME/.rvm ] ; then
    gpg --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    \curl -sSL get.rvm.io | bash -s stable
    hash -r
fi

source $HOME/.rvm/scripts/rvm
rvm install $RUBY_VERSION
rvm use --default $RUBY_VERSION
