#!/bin/sh

ruby_version=`rbenv install -l | grep -E "^[ 0-9\.]+$" | sort -V | tail -n 1`
if [ -z "`rbenv versions | grep $ruby_version`" ]; then
    rbenv install $ruby_version
    rbenv global $ruby_version
fi
