#!/bin/sh

if ! dpkg -l chefdk > /dev/null 2>&1 ; then
    filename=chefdk_0.3.5-1_amd64.deb
    wget https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/$filename -O $filename
    sudo dpkg -i $filename
    rm $filename
fi
