#!/bin/sh

if ! dpkg -l dropbox > /dev/null 2>&1 ; then
    wget "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb" -O dropbox_amd64.deb
    sudo dpkg -i dropbox_amd64.deb
    rm dropbox_amd64.deb
fi
