#!/bin/sh

if ! dpkg -l vagrant > /dev/null 2>&1 ; then
    filename=vagrant_1.6.5_x86_64.deb
    wget https://dl.bintray.com/mitchellh/vagrant/$filename -O $filename
    sudo dpkg -i $filename
    rm $filename
    vagrant plugin install vagrant-omnibus
    vagrant plugin install vagrant-berkshelf
fi
